[package]
name = "word_counter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input_conv = { path = "../libraryCrates/input_conv", version = "1.1.0" }
